# SPDX-FileCopyrightText: Public Domain
# SPDX-License-Identifier: CC0-1.0

version = 1
SPDX-PackageName = "Npp.DotNet.Plugin"
SPDX-PackageSupplier = "Npp.NET Team <https://github.com/npp-dotnet>"
SPDX-PackageDownloadLocation = "https://www.nuget.org/packages/npp.dotnet.plugin"

[[annotations]]
path = ["COPYING"]
SPDX-FileCopyrightText = "2004 Apache Software Foundation"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = ["**.json", "**.user", "doc/**", "docfx/**", "examples/**.ini", "lib/**.md", "lib/**.png", "**/CODEOWNERS", "README**", "NOTICE**"]
precedence = "aggregate"
SPDX-FileCopyrightText = "Public Domain"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = ["**.pubxml", "**.sln", "**.props", "**.targets", "**.vcxproj", "**.snk", "lib/**.csproj", "examples/**/**.csproj", "examples/**/**.fsproj", "examples/**/**.vbproj", "test/**/**.csproj"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 Robert Di Pardo"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = ["lib/**/Winforms/Classes/**.resx", "lib/**/Winforms/Classes/**.Designer.cs"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 Mark Johnston Olson"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = ["examples/gui/Properties/**", "examples/gui/Forms/**.resx", "examples/gui/Forms/**.Designer.cs"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2016 Kasper B. Graversen, 2023 Mark Johnston Olson, 2024 Robert Di Pardo"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = ["scripts/scintilla/**"]
SPDX-FileCopyrightText = "2000, 2013 Neil Hodgson <neilh@scintilla.org>"
SPDX-License-Identifier = "LicenseRef-Scintilla"
