#!/usr/bin/env bash
#
# SPDX-FileCopyrightText: (c) 2024 Robert Di Pardo
# SPDX-License-Identifier: 0BSD
#
set -e

OUTPUT="$(dirname "$0")/../lib/Npp.DotNet.Plugin/Kbg.NppPluginNET/SciMsgs.cs"
SCI_MSGS_CS_TMP='/tmp/SciMsgs.cs.tmp'
SCINTILLA_H="${1:-/tmp/Scintilla.h}"

extract_messages() {
  :>"$2"
  FROM=$(grep -nE '(\+\+Autogenerated)' "$1" | cut -f1 -d:)
  TO=$(grep -nE '(\-\-Autogenerated)' "$1" | cut -f1 -d:)
  sed -n "$FROM,$TO p" "$1" | awk '
    {gsub(/\r/,"",$0)};
    /^#define/{sub(/\-1$/,"0xFFFFFFFF",$3);print "        "$2,"=",$3","}
    /^#(if|end)(n?def|if)/{r=sub(/(ndef)$/,"",$1);if(r>0) print $1,"!"$2; else {sub(/(def)$/,"",$1);print $1,$2}}
  ' >> "$2"
}

cat <<-CS > "$OUTPUT"
/*
 * SPDX-FileCopyrightText: $(date +'%Y') $(git config --get user.name) <$(git config --get user.email)>
 *
 * SPDX-License-Identifier: Apache-2.0
 */

using System;

namespace Npp.DotNet.Plugin
{
    // Autogenerated $(date +'%Y-%m-%d')
    [Flags]
    public enum SciMsg : uint
    {
CS

[ ! -f "$SCINTILLA_H" ] && \
  curl -sLJ 'https://raw.githubusercontent.com/notepad-plus-plus/notepad-plus-plus/master/scintilla/include/Scintilla.h' \
    -o "$SCINTILLA_H"
extract_messages "$SCINTILLA_H" "$SCI_MSGS_CS_TMP"

while IFS= read -r line; do
  MSG="$(echo "${line//=/}" | awk '{print $1}' | grep -iE '^SC' || true)"
  [ -n "$MSG" ] && \
    PYTHONIOENCODING=utf-8 "$(dirname "$0")"/get_sci_doc.py "$MSG" 2>/dev/null >> "$OUTPUT"
  printf "%s\r\n" "$line" >> "$OUTPUT"
done < "$SCI_MSGS_CS_TMP"

cat <<-CS >> "$OUTPUT"
    }
}
CS

# trim trailing space
sed -e 's/[[:space:]]*$//' -i "$OUTPUT"
# try to keep line-endings consistent
unix2dos -k -m -u "$OUTPUT"
