# SPDX-FileCopyrightText: Public Domain
# SPDX-License-Identifier: CC0-1.0

name: NuGet
on:
  push:
    tags:
      - '**'

permissions:  # added using https://github.com/step-security/secure-repo
  contents: read

jobs:
  package:
    runs-on: windows-latest
    concurrency:
      group: rel-${{ github.ref_name }}
      cancel-in-progress: true
    permissions:
      id-token: write # required by NuGet/login
    env:
      DOTNET_NOLOGO: true
      DOTNET_CLI_TELEMETRY_OPTOUT: true

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
          fetch-depth: 0
      - uses: Sactions/setup-dotnet@c2fa09f4bde5ebb9d1777cf28262a3eb3db3ced7 # v5.2.0
        with:
          global-json-file: ./global.json

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@30375c66a4eea26614e0d39710365f22f8b0af57 # v3.0.0

      - name: Build package
        run: |
          dotnet restore
          .\scripts\pack.ps1

      - name: Obtain NuGet API key
        uses: NuGet/login@d22cc5f58ff5b88bf9bd452535b4335137e24544 # v1.1.0
        id: login
        with:
          user: ${{ secrets.NUGET_USER }}

      - name: Publish release
        working-directory: ./lib/bin/Release
        run: |
          dotnet nuget push Npp.DotNet.Plugin.${env:RELEASE}.nupkg -k ${env:API_KEY} -s https://api.nuget.org/v3/index.json --skip-duplicate
        env:
          RELEASE: ${{ github.ref_name }}
          API_KEY: ${{ steps.login.outputs.NUGET_API_KEY }}
